CREATE DATABASE travel_agency;

USE travel_agency;

CREATE TABLE branch
(branch_code INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
branch_street VARCHAR(30) NOT NULL,
branch_num INT(4) UNSIGNED NOT NULL,
branch_city VARCHAR(30) NOT NULL,
PRIMARY KEY(branch_code));

CREATE TABLE phones
(phones_br_code INT(11) UNSIGNED NOT NULL,
phones_number CHAR(10) NOT NULL,
PRIMARY KEY(phones_br_code,phones_number),
CONSTRAINT BRANCHPHONES 
FOREIGN KEY(phones_br_code) REFERENCES branch(branch_code)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE worker
(worker_AT CHAR(10) NOT NULL, 
worker_name VARCHAR(20) DEFAULT 'unknown' NOT NULL,
worker_lname VARCHAR(20) DEFAULT 'unknown' NOT NULL,
worker_salary FLOAT(7,2) UNSIGNED NOT NULL, 
worker_br_code INT(11) UNSIGNED NOT NULL, 
PRIMARY KEY(worker_AT),
CONSTRAINT WORKERBRANCH
FOREIGN KEY(worker_br_code) REFERENCES branch(branch_code)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE admin
(admin_AT CHAR(10) NOT NULL,
admin_type ENUM('LOGISTICS','ADMINISTRATIVE','ACCOUNTING') NOT NULL,
admin_diploma VARCHAR(200) NOT NULL,
PRIMARY KEY(admin_AT),
CONSTRAINT ADMINWORKER 
FOREIGN KEY(admin_AT) REFERENCES worker(worker_AT)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE manages
(mng_adm_AT CHAR(10) NOT NULL,
mng_br_code INT(11) UNSIGNED NOT NULL,
PRIMARY KEY(mng_adm_AT,mng_br_code),
CONSTRAINT ADMINMANAGES
FOREIGN KEY(mng_adm_AT) REFERENCES admin(admin_AT),
CONSTRAINT MANAGESBRANCH
FOREIGN KEY(mng_br_code) REFERENCES branch(branch_code)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE driver
(driver_AT CHAR(10) NOT NULL,
driver_licence ENUM('A','B','C','D') NOT NULL,
driver_route ENUM('LOCAL','ABROAD') NOT NULL,
driver_experience TINYINT(4) UNSIGNED NOT NULL,
PRIMARY KEY(driver_AT),
CONSTRAINT DRIVERWORKER 
FOREIGN KEY(driver_AT) REFERENCES worker(worker_AT)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE guide
(guide_AT CHAR(10) NOT NULL,
guide_cv TEXT,
PRIMARY KEY(guide_AT),
CONSTRAINT GUIDEWORKER 
FOREIGN KEY(guide_AT) REFERENCES worker(worker_AT)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE languages
(lng_guide_AT CHAR(10) NOT NULL,
lng_language VARCHAR(30) NOT NULL,
PRIMARY KEY(lng_guide_AT,lng_language),
CONSTRAINT GUIDELNGS 
FOREIGN KEY(lng_guide_AT) REFERENCES guide(guide_AT)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE trip
(tr_id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
tr_departure DATETIME NOT NULL,
tr_return DATETIME NOT NULL,
tr_maxseats TINYINT(4) UNSIGNED NOT NULL,
tr_cost FLOAT(7,2) UNSIGNED NOT NULL,
tr_br_code INT(11) UNSIGNED NOT NULL,
tr_gui_AT CHAR(10) NOT NULL,
tr_drv_AT CHAR(10) NOT NULL,
PRIMARY KEY(tr_id),
CONSTRAINT BRANCHTRIP
FOREIGN KEY(tr_br_code) REFERENCES branch(branch_code),
CONSTRAINT GUIDETRIP
FOREIGN KEY(tr_gui_AT) REFERENCES guide(guide_AT),
CONSTRAINT DRIVERTRIP
FOREIGN KEY(tr_drv_AT) REFERENCES driver(driver_AT)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE event
(ev_tr_id INT(11) UNSIGNED NOT NULL,
ev_start DATETIME NOT NULL,
ev_end DATETIME NOT NULL,
ev_descr TEXT NOT NULL,
PRIMARY KEY(ev_tr_id),
CONSTRAINT TRIPEVENT
FOREIGN KEY(ev_tr_id) REFERENCES trip(tr_id)
ON DELETE CASCADE ON UPDATE CASCADE);
 
CREATE TABLE reservation
(res_tr_id INT(11) UNSIGNED NOT NULL,
res_seatnum TINYINT(4) UNSIGNED NOT NULL,
res_name VARCHAR(20) DEFAULT 'unknown' NOT NULL,
res_lname VARCHAR(20) DEFAULT 'unknown' NOT NULL,
res_isadult ENUM('ADULT','MINOR') NOT NULL,
PRIMARY KEY(res_seatnum),
CONSTRAINT TRIPRESERVED
FOREIGN KEY(res_tr_id) REFERENCES trip(tr_id)
ON DELETE CASCADE ON UPDATE CASCADE);
  
CREATE TABLE destination
(dst_id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
dst_name VARCHAR(50) NOT NULL,
dst_descr  TEXT NOT NULL,
dst_rtype ENUM('LOCAL','ABROAD') NOT NULL,
dst_language VARCHAR(30) NOT NULL,
dst_location INT(11) UNSIGNED NOT NULL,
PRIMARY KEY(dst_id));
   
   /* ADD SELF REFERENCE OF DESTINATION*/
   
ALTER TABLE destination
ADD CONSTRAINT DESTSELFREFERENCE
FOREIGN KEY(dst_location) REFERENCES destination(dst_id);
   
CREATE TABLE travel_to
(to_tr_id INT(11) UNSIGNED NOT NULL,
to_dst_id INT(11) UNSIGNED NOT NULL,
to_arrival DATETIME NOT NULL,
to_departure DATETIME NOT NULL,
PRIMARY KEY(to_tr_id),
CONSTRAINT TRIPTRAVELTO
FOREIGN KEY(to_tr_id) REFERENCES trip(tr_id),
CONSTRAINT TRAVELTODESTINATION
FOREIGN KEY(to_dst_id) REFERENCES destination(dst_id)
ON DELETE CASCADE ON UPDATE CASCADE);


/* INSERTIONS INTO THE REQUESTED TABLES */

/* BRANCH INSERTIONS */


INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("KWSTH PALAMA",30,"AGIOI THEODOROI");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("KASTORIAS",35,"ATHINA");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("LEWFOROS KIFHSOY",97,"ATHINA");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("MONEMVASIAS",36,"ATHINA");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("PRAKSIOY",10,"ATHINA");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("PAGASWN",99,"VOLOS");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("AGOURIDOU",3,"ITEA");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("FARWN",128,"KALAMATA");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("ETHNIKIS ANTISTASEWS",38,"KORINTHOS");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("ATHANASIADH NOVA",90,"NAUPAKTOS");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("AKRWTHRIOY",120,"PATRA");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("PANEPISTIMIOY",200,"PATRA");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("RHGA FERAIOY",35,"PATRA");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("DELHGIWRGH",25,"PEIRAIAS");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("YMHTTOY",88,"PEIRAIAS");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("TSIMISKI",90,"THESSALONIKH");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("LEWFOROS NIKHS",130,"THESSALONIKH");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("ARISTOTELOYS",200,"THESSALONIKH");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("VRASIDOU",32,"SPARTH");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("SALAMINOS",10,"XALKIDA");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("GERASIMOU",34,"XANIA");

INSERT INTO branch(branch_street,branch_num,branch_city) VALUES
("ARSINOIS",20,"XIOS");

/* INSERTIONS INTO PHONES */

INSERT INTO phones VALUES
(1,"2104350697");

INSERT INTO phones VALUES
(2,"2119570000");

INSERT INTO phones VALUES
(3,"2108899318");

INSERT INTO phones VALUES
(4,"2421033567");

INSERT INTO phones VALUES
(5,"2265010020");

INSERT INTO phones VALUES
(6,"2721055790");

INSERT INTO phones VALUES
(7,"2741033051");

INSERT INTO phones VALUES
(8,"2634000910");

INSERT INTO phones VALUES
(9,"2610993122");

INSERT INTO phones VALUES
(10,"2610990077");

INSERT INTO phones VALUES
(11,"2610230080");

INSERT INTO phones VALUES
(12,"2108090078");

INSERT INTO phones VALUES
(13,"2104545633");

INSERT INTO phones VALUES
(14,"2310708000");

INSERT INTO phones VALUES
(15,"2310334477");

INSERT INTO phones VALUES
(16,"2310324856");

INSERT INTO phones VALUES
(17,"3731060700");

INSERT INTO phones VALUES
(18,"2221099310");

INSERT INTO phones VALUES
(19,"2821067059");

INSERT INTO phones VALUES
(20,"2271070500");

/* INSERTIONS IN WORKER */

/* WORKERS OF BRANCH 1*/

INSERT INTO worker VALUES
("AB102210","GEWRGIOS","HLIOPOULOS",800,1); /* driver */

INSERT INTO worker VALUES
("AN272428","HLIANNA","GEWRGAKOPOYLOY",800,1); /* driver */

INSERT INTO worker VALUES
("AI212134","IWANNIS","ANASTASIOU",1500,1); /* admin */

INSERT INTO worker VALUES
("AH987765","PANAGIWTHS","TSAROUXIS",1100,1); /* guide */

/* WORKERS OF BRANCH 2 */

INSERT INTO worker VALUES
("AI584736","VASILIKI","MAXA",1500,2); /*ADMIN*/

INSERT INTO worker VALUES
("AK101314","AGGELOS","KOYMANIWTHS",800,2); /*DRIVER */

INSERT INTO worker VALUES
("AH171822","ANTREAS","NTOFIS",800,2); /* DRIVER */

INSERT INTO worker VALUES
("AM232341","GEWRGIOS","SARIDAKIS",1100,2); /* GUIDE */

/* WORKERS OF BRANCH 3 */

INSERT INTO worker VALUES
("AY756512","PANAGIWTA","VELISSARH",800,3); /* DRIVER */

INSERT INTO worker VALUES
("P918213","IWANNIS","KYRIAKOPOYLOS",800,3); /* DRIVER */

INSERT INTO worker VALUES
("AB121314","XRHSTOS","ANDRIKOPOULOS",1600,3); /* ADMIN */

INSERT INTO worker VALUES
("AX676865","MARIA","NIASTH",1130,3); /* GUIDE */

/* WORKERS OF BRANCH 4 */ /*INSERTED*/

INSERT INTO worker VALUES
("AX908878","XRISTINA","KONTOGEWRGOU",870.35,4); /* DRIVER */

INSERT INTO worker VALUES
("ΑΔ120099","PARASKEYH","LINARDOY",835.60,4);/*DRIVER*/

INSERT INTO worker VALUES
("AN272481","PERIKLIS","PAPADOPOYLOS",1120.80,4);/*GUIDE*/

INSERT INTO worker VALUES
("AI991111","VASILEIOS","DHMHTROPOYLOS",1832.42,4);/*ADMIN*/

/* WORKERS OF BRANCH 5 */

INSERT INTO worker VALUES
("ΑΛ886578","ANASTASIOS","PAPADHMHTRIOY",930.21,5);

INSERT INTO worker VALUES
("AY108760","DESPOINA","OIKONOMOY",876,5);

INSERT INTO worker VALUES
("AI867544","GEWRGIOS","PATRINOS",1050.23,5);

INSERT INTO worker VALUES
("AO125677","DHMHTRIOS","PAPAXRHSTOY",1543.88,5);

/* WORKERS OF BRANCH 6 */

INSERT INTO worker VALUES
("AN990122","DIONYSIOS","THEODWROPOYLOS",870,6);

INSERT INTO worker VALUES
("AI543473","AGGELIKH","VASILEIADOY",1140.87,6);

INSERT INTO worker VALUES
("AM456097","XRISTINA","KATRITZOGLOY",830,6);

INSERT INTO worker VALUES
("Π314121","XRHSTOS","PERROS",1670,6);

/* WORKERS OF BRANCH 7 */ /*INSERTED*/

INSERT INTO worker VALUES
("AK465732","KWNSTANTINOS","XRHSTAKHS",854.90,7);

INSERT INTO worker VALUES
("AB758699","TRYFWN","DELOGLOY",890,7);

INSERT INTO worker VALUES
("AH654535","HLIAS","PAPADOPOYLOS",1700.32,7);

INSERT INTO worker VALUES
("AY121365","ANTONIA","THRYPSIALLH",1070.90,7);

/* WORKES OF BRANCH 8 */

INSERT INTO worker VALUES
("AE252632","PANAGIWTHS","KOYVELAS",900.44,8);

INSERT INTO worker VALUES
("AM657533","DHMHTRA","MWRAITH",910.65,8);

INSERT INTO worker VALUES
("AN989766","NIKOLAOS","KANELLOPOYLOS",1900.34,8);

INSERT INTO worker VALUES
("AT990233","KATERINA","PAPAIWANNOY",997.33,8);

/*WORKERS OF BRANCH 9 */

INSERT INTO worker VALUES
("AI237345","ANASTASIA","PAPADOPOYLOY",2013.38,9);

INSERT INTO worker VALUES
("AT673566","DHMHTRIOS","KALOGHROY",837.23,9);

INSERT INTO worker VALUES
("P939302","IWANNA","KYVELLH",1120,9);

INSERT INTO worker VALUES
("AN271815","MARIOS","KIOYTOYTSKAS",1024.47,9);

/* WORKERS OF BRANCH 10 */
 
INSERT INTO worker VALUES
("AB905543","GEWRGIOS","DHMHTRIOY",785.76,10);

INSERT INTO worker VALUES
("AI892193","PETROS","RAFAHLIDHS",1670.66,10);

INSERT INTO worker VALUES
("AM892191","MHNAS","ASTERIWTHS",822,10);

INSERT INTO worker VALUES
("AI921012","EYAGGELIA","TOYMPESH",1034.65,10);

/* WORKERS OF BRANCH 11 */

INSERT INTO worker VALUES
("AO873465","EIRHNH","TRYFWNIADOY",911,11);

INSERT INTO worker VALUES
("I912133","ANASTASIOS","LIOKAS",891.22,11);

INSERT INTO worker VALUES
("X721843","AGAPH","FOYNTAKH",1930.34,11);

INSERT INTO worker VALUES
("AY734190","VASILEIOS","NIKAS",1000.30,11);

/* WORKERS OF BRANCH 12 */

INSERT INTO worker VALUES
("AO125334","APOSTOLOS","NTOLEVAS",1990,12);

INSERT INTO worker VALUES
("AB374839","IWANNIS","DELHGIWRGHS",1002.34,12);

INSERT INTO worker VALUES
("P192122","PAVLOS","XANIWTHS",800.32,12);

INSERT INTO worker VALUES
("X673720","ELPIDA","XARMANI",789.39,12);
